Repository NETWAYS/ansible-collection-icinga, pull requests merged in 2021-11, with the labels that each got.

#59 Bug/55
  doc/objects.md
  plugins/modules/icinga2_service.py
Labels: cla/signed

#80 Add ConfigDir to the icinga2 reserved list
  roles/icinga2/vars/main.yml
Labels: bug, cla/signed

#86 added integration tests with molecule testinfra
  .ansible-lint
  molecule/default/converge.yml
  molecule/default/host_vars/icinga-default.yaml
  molecule/default/molecule.yml
  molecule/default/prepare.yml
  molecule/default/tests/integration/test_icinga2.py
  molecule/default/tests/integration/test_repos.py
  molecule/default/tests/integration/test_service.py
  requirements-test.txt
  roles/icinga2/tasks/configure.yml
  roles/icinga2/tasks/features/api.yml
Labels: cla/signed

#82 Add documentation snippet for CheckCommand
  doc/objects.md
Labels: documentation

#84 added unittests and github workflow
  .github/workflows/python-test.yml
  .gitignore
  tests/__init__.py
  tests/unittestpy2/__init__.py
  tests/unittestpy2/test_data.py
  tests/unittestpy3/__init__.py
  tests/unittestpy3/test_data.py
Labels: cla/signed

#60 Add object UserGroup
  doc/objects.md
  plugins/modules/icinga2_usergroup.py
  roles/icinga2/vars/main.yml
Labels: enhancement, cla/signed

#63 Enable applying to a target host or service and add object Notification
  doc/objects.md
  plugins/action/icinga2_object.py
  plugins/modules/icinga2_notification.py
  plugins/modules/icinga2_notificationcommand.py
  plugins/modules/icinga2_user.py
  roles/icinga2/vars/main.yml
Labels: enhancement, cla/signed

#65 Add object Dependency
  doc/objects.md
  molecule/default/host_vars/icinga-default.yaml
  molecule/default/tests/integration/test_dependencies.py
  plugins/modules/icinga2_dependency.py
  roles/icinga2/vars/main.yml
Labels: enhancement, cla/signed
