Repository NETWAYS/ansible-collection-icinga, pull requests merged in 2022-08, with the labels that each got.

#91 add custom config files
  molecule/default/converge.yml
  molecule/default/files/icinga2_command
  molecule/default/host_vars/icinga-default.yaml
  molecule/default/tests/integration/test_custom_file.py
  roles/icinga2/tasks/configure.yml
  roles/icinga2/tasks/objects.yml
Labels: cla/signed

#70 Add object and feature for IcingaDB
  doc/features/feature-icingadb.md
  molecule/default/converge.yml
  molecule/default/tests/integration/test_icingadb_config.py
  plugins/modules/icinga2_icingadb.py
  roles/icinga2/tasks/features/icingadb.yml
  roles/icinga2/vars/main.yml
Labels: enhancement, cla/signed

#102 Enhancement/refresh documentation
  README.md
  doc/getting-started.md
Labels: cla/signed

#69 Add object and feature for OpenTsdbWriter
  doc/features/feature-opentsdb.md
  molecule/default/converge.yml
  molecule/default/tests/integration/test_icinga2.py
  plugins/modules/icinga2_opentsdbwriter.py
  roles/icinga2/tasks/features/opentsdb.yml
  roles/icinga2/vars/main.yml
Labels: enhancement, cla/signed

#66 Add object and feature for ElasticsearchWriter
  README.md
  doc/features/feature-elasticsearch.md
  molecule/default/converge.yml
  molecule/default/tests/integration/test_icinga2.py
  plugins/modules/icinga2_elasticsearchwriter.py
  roles/icinga2/tasks/features/elasticsearch.yml
  roles/icinga2/vars/main.yml
Labels: enhancement, cla/signed

#103 Added documentation for custom config
  README.md
  doc/role-icinga2.md
  doc/role-repos.md
Labels: cla/signed

#67 Add object and feature for GelfWriter
  README.md
  doc/features/feature-gelf.md
  molecule/default/converge.yml
  molecule/default/tests/integration/test_icinga2.py
  plugins/modules/icinga2_gelfwriter.py
  roles/icinga2/tasks/features/gelf.yml
  roles/icinga2/vars/main.yml
Labels: enhancement, cla/signed

#68 Add object and feature for PerfdataWriter
  README.md
  doc/features/feature-perfdata.md
  molecule/default/converge.yml
  molecule/default/tests/integration/test_icinga2.py
  plugins/modules/icinga2_perfdatawriter.py
  roles/icinga2/tasks/features/perfdata.yml
  roles/icinga2/vars/main.yml
Labels: enhancement, cla/signed

#104 fix empty custom config
  roles/icinga2/defaults/main.yml
  roles/icinga2/tasks/features/api.yml
  roles/icinga2/tasks/objects.yml
Labels: cla/signed

#106 support icinga2_objects var outside of hostvars
  .github/workflows/build.yml
  molecule/default/host_vars/icinga-default.yaml
  roles/icinga2/tasks/objects.yml
Labels: cla/signed

#108 rework documentation structure
  .github/workflows/build.yml
  .github/workflows/python-test.yml
  README.md
  doc/getting-started.md
  doc/role-icinga2/features.md
  doc/role-icinga2/features/feature-api.md
  doc/role-icinga2/features/feature-command.md
  doc/role-icinga2/features/feature-elasticsearch.md
  doc/role-icinga2/features/feature-gelf.md
  doc/role-icinga2/features/feature-graphite.md
  doc/role-icinga2/features/feature-icingadb.md
  doc/role-icinga2/features/feature-ido.md
  doc/role-icinga2/features/feature-influxdb.md
  doc/role-icinga2/features/feature-influxdb2.md
  doc/role-icinga2/features/feature-mainlog.md
  doc/role-icinga2/features/feature-notification.md
  doc/role-icinga2/features/feature-opentsdb.md
  doc/role-icinga2/objects.md
  doc/role-icinga2/role-icinga2.md
  doc/role-repos/role-repos.md
Labels: cla/signed

#110 Add object and feature LiveStatusListener
  doc/role-icinga2/features.md
  doc/role-icinga2/features/feature-influxdb2.md
  doc/role-icinga2/features/feature-livestatus.md
  doc/role-icinga2/features/feature-perfdata.md
  plugins/modules/icinga2_livestatuslistener.py
  roles/icinga2/tasks/features/livestatus.yml
  roles/icinga2/vars/main.yml
Labels: cla/signed

#111 Add pylint to CI Workflows
  .github/workflows/python-test.yml
  .pylintrc
  Makefile
  plugins/action/icinga2_object.py
  plugins/filter/prefix.py
  plugins/lookup/icinga2_parser.py
  plugins/module_utils/parse.py
  plugins/modules/icinga2_elasticsearchwriter.py
  plugins/modules/icinga2_gelfwriter.py
  plugins/modules/icinga2_icingadb.py
  plugins/modules/icinga2_influxdb2writer.py
  plugins/modules/icinga2_opentsdbwriter.py
  plugins/modules/icinga2_perfdatawriter.py
Labels: cla/signed

#115 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cla/signed

#114 CA Host port should be manageable
  .github/workflows/build.yml
  roles/icinga2/tasks/features/api.yml
Labels: cla/signed

#109 Add validation of CA fingerprint during certificate requests
  .github/workflows/build.yml
  doc/role-icinga2/features/feature-api.md
  roles/icinga2/tasks/features/api.yml
Labels: cla/signed

#97 Add support for Fedora
  .github/workflows/build.yml
  roles/repos/vars/RedHat-Fedora.yml
Labels: feature, cla/signed

#117 Add icinga2_config_host var
  doc/role-icinga2/features/feature-api.md
  roles/icinga2/defaults/main.yml
  roles/icinga2/tasks/objects.yml
Labels: cla/signed
