Repository NETWAYS/ansible-collection-icinga, pull requests merged in 2023-12, with the labels that each got.

#239 Updates documentation for IcingaDB schema management
  doc/role-icingadb/role-icingadb.md
Labels: docs, cla/signed

#220 Fix/director installation
  changelogs/fragments/feature_adjust_director_source_installation.yml
  roles/icingaweb2/tasks/modules/director.yml
Labels: bug, cla/signed

#222 Adds possibility to delegate ticket creation to satellites
  changelogs/fragments/feature_add_satellite_delegation.yml
  doc/role-icinga2/features/feature-api.md
  roles/icinga2/tasks/features/api.yml
Labels: feature, cla/signed

#246 remove superfluous curly brace
  roles/icinga2/tasks/features/api.yml
Labels: bug, cla/signed

#248 Adjusts variable lookups
  changelogs/fragments/minor_change_adjust_vars_lookup.yml
  roles/icingaweb2/tasks/modules/businessprocess.yml
  roles/icingaweb2/tasks/modules/director.yml
  roles/icingaweb2/tasks/modules/manage_module_config.yml
  roles/icingaweb2/tasks/modules/x509.yml
Labels: bug, cla/signed

#241 execute the pgsqlcmd with LANG=C to make sure the output is in english and we can match for '(0 rows)' in the next task
  roles/icingaweb2/tasks/manage_icingaweb_pgsql_db.yml
Labels: cla/signed

#250 added missing quotes to ticket delegation
  changelogs/fragments/fix_missing_quotes_delegate_ticket.yml
  roles/icinga2/tasks/features/api.yml
Labels: bug, cla/signed
