Repository NETWAYS/ansible-collection-icinga, pull requests merged in 2023-11, with the labels that each got.

#203 support Raspbian armhf repos
  roles/repos/tasks/main.yml
  roles/repos/vars/Debian-Raspbian.yml
Labels: cla/signed

#202 Adds password capabilities to icingadb-redis configuration
  doc/role-icingadb_redis/role-icingadb_redis.md
  roles/icingadb_redis/templates/icingadb-redis.conf.j2
Labels: cla/signed

#207 Fixed typo in api.yml
  changelogs/fragments/fixed_typo_in_api_yml_file.yml
  roles/icinga2/tasks/features/api.yml
Labels: cla/signed

#210 Fix incorrect cycle of installation and removal
  changelogs/fragments/bugfix-monitoring-plugins-installation-removal-cycle.yml
  roles/monitoring_plugins/tasks/install_on_Debian.yml
  roles/monitoring_plugins/tasks/install_on_RedHat.yml
Labels: cla/signed

#215 Adjusts actions so scenarios don't **always** run
  .github/workflows/build.yml
Labels: cla/signed

#214 add installation for x509 module
  changelogs/fragments/feature_add_x509_module_installation.yml
  doc/role-icingaweb2/module-x509.md
  roles/icingaweb2/tasks/main.yml
  roles/icingaweb2/tasks/manage_mysql_imports.yml
  roles/icingaweb2/tasks/modules/x509.yml
  roles/icingaweb2/vars/main.yml
Labels: feature, cla/signed

#216 Adds docs on database setup
  doc/getting-started.md
  doc/role-icingadb/role-icingadb.md
  doc/role-icingaweb2/role-icingaweb2.md
Labels: docs, cla/signed
