Repository NETWAYS/ansible-collection-icinga, pull requests merged in 2024-01, with the labels that each got.

#254 Fix module configuration task order
  changelogs/fragments/fix_change_order_of_module_tasks.yml
  roles/icingaweb2/tasks/main.yml
Labels: cla/signed

#244 icingaweb: fix duplicate task name, the second one runs the kickstart, if required
  roles/icingaweb2/tasks/modules/director.yml
Labels: cla/signed

#177 Feature/ansible inventory
  .github/workflows/python-test.yml
  README.md
  changelogs/fragments/feature_ansible_inventory.yml
  doc/getting-started.md
  doc/plugins/inventory/icinga-inventory-plugin.md
  plugins/inventory/icinga.py
  tests/unittestpy3/test_inventory.py
Labels: feature, cla/signed

#209 Add variable for dependency repositories within monitoring_plugins role
  changelogs/fragments/fix-173-changeable-dependency-repos.yml
  doc/role-monitoring_plugins/role-monitoring_plugins.md
  roles/monitoring_plugins/defaults/main.yml
  roles/monitoring_plugins/tasks/install_on_RedHat.yml
Labels: cla/signed

#253 Feature/enhance icingadb retention config
  changelogs/fragments/feature_enhance_icingadb_retention_configs.yml
  doc/role-icingadb/role-icingadb.md
  molecule/default/host_vars/icinga-default.yaml
  molecule/default/tests/integration/test_icingadb_retentions.py
  molecule/local-default/host_vars/icinga-default.yaml
  molecule/local-default/molecule.yml
  molecule/local-default/tests/integration/test_icingadb_retentions.py
  roles/icingadb/templates/icingadb.ini.j2
Labels: feature, cla/signed

#255 Fix 228 collect of icinga2_objects
  changelogs/fragments/fix_issue_228.yml
  roles/icinga2/tasks/objects.yml
Labels: cla/signed

#257 removed localhost condition as default
  molecule/local-default-pgsql/converge.yml
  roles/icingadb/tasks/manage_schema_pgsql.yml
Labels: cla/signed

#221 Adds PostgresQL support for Icingaweb2 modules
  changelogs/fragments/feature_add_pgsql_support_for_modules.yml
  roles/icingaweb2/tasks/modules/manage_pgsql_imports.yml
  roles/icingaweb2/tasks/modules/x509.yml
Labels: feature, cla/signed

#258 Fix/proper fail on unsupported os
  changelogs/fragments/minor_changes.yml
  roles/icinga2/tasks/install.yml
  roles/icingadb/tasks/main.yml
  roles/icingadb_redis/tasks/main.yml
  roles/icingaweb2/tasks/main.yml
  roles/monitoring_plugins/tasks/main.yml
  roles/repos/tasks/main.yml
Labels: bug, cla/signed
